### ISSUE TITLE
统一tab和换一换的按钮样式

### ISSUE THREAD

**Issue by nothingshiru** [magicdawn/bilibili-app-recommend#40]
目前tab按钮的高度偏小，图标和文字又偏大，看起来略显拥挤。希望可以调节统一一下
![image](https://github.com/magicdawn/bilibili-app-recommend/assets/79258245/9f48f8fb-aa94-4508-9b9e-873b0c41bda5)

**Comment by magicdawn** [comment]
em...小巧点不好么! 我自己挺满意的~

**Comment by magicdawn** [comment]
em...默认我自己很满意, 就不动了...

这边提供一个自定义方法

- 安装 [stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne)
- 安装 https://userstyles.world/style/10382/bilibili-app-recommend-tab


---------
代码为

```css
.ant-radio-button-wrapper.video-source-tab {
  height: 32px;
  line-height: 32px;
}
```

自己用 stylus 新建样式也行

---------

`.video-source-tab` 从 0.14.1 开始. 现在 0.14.0 还没有
