### ISSUE TITLE
统一卡片里按钮的图标尺寸

### ISSUE THREAD

**Issue by nothingshiru** [magicdawn/bilibili-app-recommend#93]
这几个图标的尺寸，一个是13x13，一个是16x16，一个是20x20
![屏幕截图 2024-05-12 014301](https://github.com/magicdawn/bilibili-app-recommend/assets/79258245/8ac165e3-b001-4479-ba8c-cf760292e79c)

可以把它们统一成20x20吗？这样好看些
![屏幕截图 2024-05-12 015943](https://github.com/magicdawn/bilibili-app-recommend/assets/79258245/a9825806-081e-4118-a2c7-8505064bff12)

**Comment by magicdawn** [comment]
Q: 是故意的还是不小心
A: 是故意的

统一大小很丑啊，尤其是前两个，不需要那么大，小窗打开图标大了快吐了。

既然你能自己改，自己用 stylish 之类插件覆盖吧

**Comment by magicdawn** [comment]
安装最新开发版后, 可以这样自定义

```css
.bilibili-app-recommend-root .bili-video-card .action-button svg {
  width: 20px;
  height: 20px;
}
```

使用 https://chromewebstore.google.com/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne stylus 新建一个样式即可.
